FROM node:20-alpine AS base

RUN apk add jq openssh openssh-server openssh-keygen supervisor
RUN ssh-keygen -A
RUN adduser -D -s /bin/sh devuser \
  && mkdir -p /home/devuser/.ssh \
  && chmod 700 /home/devuser/.ssh
RUN echo "PermitRootLogin no" >> /etc/ssh/sshd_config \
  && echo "PasswordAuthentication no" >> /etc/ssh/sshd_config \
  && echo "PubkeyAuthentication yes" >> /etc/ssh/sshd_config \
  && echo "AuthorizedKeysFile /home/devuser/.ssh/authorized_keys" >> /etc/ssh/sshd_config \
  && echo "AllowUsers devuser" >> /etc/ssh/sshd_config
RUN echo '#!/bin/sh' > /entrypoint.sh \
  && echo 'mkdir -p /home/devuser/.ssh' >> /entrypoint.sh \
  && echo 'echo "$SSH_PUBLIC_KEY" > /home/devuser/.ssh/authorized_keys' >> /entrypoint.sh \
  && echo 'chown -R devuser:devuser /home/devuser/.ssh' >> /entrypoint.sh \
  && echo 'chmod 600 /home/devuser/.ssh/authorized_keys' >> /entrypoint.sh \
  && echo 'passwd -u devuser' >> /entrypoint.sh \
  && echo '/usr/bin/supervisord -c /etc/supervisord.conf' >> /entrypoint.sh \
  && chmod +x /entrypoint.sh
WORKDIR /app

FROM base AS development
COPY filesystem ./filesystem
RUN cd ./filesystem && npm ci
RUN for dir in $(jq ".references[].path" ./filesystem/tsconfig.json); do \
  (cd "${dir:2:-1}" && npm ci); \
  done
COPY envs/supervisord-dev.conf /etc/supervisord.conf
EXPOSE 22
ENTRYPOINT ["/entrypoint.sh"]

FROM base AS builder
COPY filesystem ./filesystem
RUN cd ./filesystem && npm ci
RUN for dir in $(jq ".references[].path" ./filesystem/tsconfig.json); do \
  (cd "${dir:2:-1}" && npm ci); \
  done
RUN npm run build --prefix filesystem

FROM base AS production
COPY --from=builder /app/filesystem/dist ./filesystem/dist
COPY --from=builder /app/filesystem/package.json ./filesystem/package.json
COPY --from=builder /app/filesystem/package-lock.json ./filesystem/package-lock.json
COPY --from=builder /app/filesystem/node_modules ./filesystem/node_modules
COPY envs/supervisord.conf /etc/supervisord.conf
EXPOSE 22
ENTRYPOINT ["/entrypoint.sh"]