services:
  filesystem:
    build:
      context: ../
      dockerfile: filesystem/dockerfile
      target: development
    image: hide-env-filesystem
    volumes:
      - .:/app/filesystem
      - /app/filesystem/node_modules
    environment:
      - NODE_ENV=development
      - SERVICE_PORT=80
      - RMQ_URL=amqp://rabbitmq:5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: [ "/bin/sh", "-c", "cd filesystem && npm run start:dev" ]
