FROM node:20-alpine AS base
RUN apk add jq
WORKDIR /app

FROM base AS development
COPY filesystem ./filesystem
RUN cd ./filesystem && npm ci
RUN for dir in $(jq ".references[].path" ./filesystem/tsconfig.json); do \
  (cd "${dir:2:-1}" && npm ci); \
  done
CMD ["/bin/sh", "-c", "cd filesystem && npm run start:dev"]

FROM base AS builder
COPY filesystem ./filesystem
RUN cd ./filesystem && npm ci
RUN for dir in $(jq ".references[].path" ./filesystem/tsconfig.json); do \
  (cd "${dir:2:-1}" && npm ci); \
  done
RUN npm run build --prefix filesystem

FROM base AS production
COPY --from=builder /app/filesystem/dist ./filesystem/dist
COPY --from=builder /app/filesystem/package.json ./filesystem/package.json
COPY --from=builder /app/filesystem/package-lock.json ./filesystem/package-lock.json
COPY --from=builder /app/filesystem/node_modules ./filesystem/node_modules
COPY --from=builder /app/libs ./libs
CMD ["/bin/sh", "-c", "cd filesystem && npm run start:prod"]
