FROM hide-env-base AS base

RUN mkdir /workspace \
  && chown -R devuser:devuser /workspace

RUN echo 'export PATH=$PATH:/usr/local/go/bin:/home/devuser/go/bin' >> /home/devuser/.profile \
  && echo 'export GOPATH=/home/devuser/go' >> /home/devuser/.profile

COPY motd /etc/motd
WORKDIR /workspace

EXPOSE 22
ENTRYPOINT ["/entrypoint.sh"]

FROM base AS development


FROM base AS production
