FROM hide-env-base AS base

RUN mkdir /workspace \
  && chown -R devuser:devuser /workspace

RUN apk add php composer
RUN echo 'export PATH=$PATH:/home/devuser/.composer/vendor/bin' >> /home/devuser/.profile

COPY motd /etc/motd
WORKDIR /workspace

FROM base AS development


FROM base AS production
