networks:
  hide-network:
    name: hide-server_hide-network
    external: true

services:
  filesystem:
    container_name: filesystem
    hostname: filesystem
    # depends_on:
    #   redis:
    #     condition: service_started
    #   rabbitmq:
    #     condition: service_started
    extends:
      file: ./filesystem/docker-compose.dev.yml
      service: filesystem
    networks:
      - hide-network
