FROM hide-env-base AS base

RUN mkdir /workspace \
  && chown -R devuser:devuser /workspace

RUN apk add --no-cache nodejs npm

USER devuser
RUN npm config set prefix /home/devuser/.npm-global
USER root

RUN echo 'export PATH=$PATH:/home/devuser/.npm-global/bin' >> /home/devuser/.profile

COPY motd /etc/motd
WORKDIR /workspace

EXPOSE 22
ENTRYPOINT ["/entrypoint.sh"]

FROM base AS development


FROM base AS production
