FROM node:20-alpine

RUN apk add --no-cache openssh openssh-server openssh-keygen
RUN ssh-keygen -A

RUN adduser -D -s /bin/sh devuser \
  && mkdir -p /home/devuser/.ssh \
  && chmod 700 /home/devuser/.ssh

RUN echo "PermitRootLogin no" >> /etc/ssh/sshd_config \
  && echo "PasswordAuthentication no" >> /etc/ssh/sshd_config \
  && echo "PubkeyAuthentication yes" >> /etc/ssh/sshd_config \
  && echo "AuthorizedKeysFile /home/devuser/.ssh/authorized_keys" >> /etc/ssh/sshd_config \
  && echo "AllowUsers devuser" >> /etc/ssh/sshd_config

RUN echo '#!/bin/sh' > /entrypoint.sh \
  && echo 'mkdir -p /home/devuser/.ssh' >> /entrypoint.sh \
  && echo 'echo "$SSH_PUBLIC_KEY" > /home/devuser/.ssh/authorized_keys' >> /entrypoint.sh \
  && echo 'chown -R devuser:devuser /home/devuser/.ssh' >> /entrypoint.sh \
  && echo 'chmod 600 /home/devuser/.ssh/authorized_keys' >> /entrypoint.sh \
  && echo 'passwd -u devuser' >> /entrypoint.sh \
  && echo 'exec /usr/sbin/sshd -D -ddd' >> /entrypoint.sh \
  && chmod +x /entrypoint.sh

EXPOSE 22

ENTRYPOINT ["/entrypoint.sh"]
