FROM hide-env-base-dev AS development

RUN mkdir /home/devuser/workspace
EXPOSE 22
ENTRYPOINT ["/entrypoint.sh"]

FROM hide-env-base AS production

RUN mkdir /home/devuser/workspace
EXPOSE 22
ENTRYPOINT ["/entrypoint.sh"]