networks:
  hide-network:
    name: hide-server_hide-network
    external: true

name: hide-env
services:
  default:
    container_name: default
    image: hide-env-dev
    build:
      context: .
      target: development
    volumes:
      - ../../filesystem:/app/filesystem
      - /app/filesystem/.build
    environment:
      - NODE_ENV=development
      - SERVICE_PORT=80
      - RMQ_URL=amqp://rabbitmq:5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - EVENT_QUEUE_SIZE=100
      - WS_UUID=default
    networks:
      - hide-network
