FROM hideregistry.azurecr.io/hide-env-base AS base

RUN mkdir /workspace \
  && chown -R devuser:devuser /workspace

COPY motd /etc/motd
WORKDIR /workspace

FROM base AS development


FROM base AS production
