ARG BASE_IMAGE=hideregistry.azurecr.io/hide-env-base
FROM ${BASE_IMAGE} AS base

RUN mkdir /workspace \
  && chown -R devuser:devuser /workspace

COPY motd /etc/motd
WORKDIR /workspace

FROM base AS development


FROM base AS production
