FROM hide-env-base AS base

RUN mkdir /workspace \
  && chown -R devuser:devuser /workspace

COPY motd /etc/motd
WORKDIR /workspace

EXPOSE 22
ENTRYPOINT ["/entrypoint.sh"]

FROM base AS development


FROM base AS production
