[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
logfile_backups=0
loglevel=info

[program:sshd]
command=/usr/sbin/sshd -D
stdout_logfile=/dev/fd/1
stderr_logfile=/dev/fd/2
stdout_logfile_maxbytes = 0
stderr_logfile_maxbytes = 0
stdout_logfile_backups=0
stderr_logfile_backups=0
process_name=sshd

[program:filesystem]
directory=/app/filesystem
command=npm run start:prod
stdout_logfile=/dev/fd/1
stderr_logfile=/dev/fd/2
stdout_logfile_maxbytes = 0
stderr_logfile_maxbytes = 0
stdout_logfile_backups=0
stderr_logfile_backups=0
process_name=filesystem
autostart=true
autorestart=true