[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
logfile_backups=0
loglevel=info

[program:sshd]
command=/usr/sbin/sshd -D -ddd
stdout_logfile=/dev/fd/1
stderr_logfile=/dev/fd/2
stdout_logfile_maxbytes = 0
stderr_logfile_maxbytes = 0
stdout_logfile_backups=0
stderr_logfile_backups=0
process_name=sshd

[program:env_gateway]
directory=/app/env-gateway
command=npm run start:dev
stdout_logfile=/dev/fd/1
stderr_logfile=/dev/fd/2
stdout_logfile_maxbytes = 0
stderr_logfile_maxbytes = 0
stdout_logfile_backups=0
stderr_logfile_backups=0
process_name=env_gateway
autostart=true
autorestart=true

[program:filesystem]
directory=/app/filesystem
command=air -c .air.toml
stdout_logfile=/dev/fd/1
stderr_logfile=/dev/fd/2
stdout_logfile_maxbytes = 0
stderr_logfile_maxbytes = 0
stdout_logfile_backups=0
stderr_logfile_backups=0
process_name=filesystem
autostart=true
autorestart=true
