FROM hide-env-base-dev AS development

RUN mkdir /workspace
RUN chown -R devuser:devuser /workspace
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

RUN apk add deno

EXPOSE 22
ENTRYPOINT ["/entrypoint.sh"]

FROM hide-env-base AS production

RUN mkdir /workspace
RUN chown -R devuser:devuser /workspace
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
EXPOSE 22
ENTRYPOINT ["/entrypoint.sh"]
