FROM hide-env-base AS base

RUN mkdir /workspace \
  && chown -R devuser:devuser /workspace

ENV PIP_BREAK_SYSTEM_PACKAGES=1
ENV VENV_PATH=/workspace/.venv
RUN apk add python3 py3-pip \
  && if [ ! -d "$VENV_PATH" ]; then python3 -m venv "$VENV_PATH"; fi \
  && echo 'export PATH=$PATH:/home/devuser/.local/bin:$VENV_PATH/bin' >> /home/devuser/.profile

COPY motd /etc/motd
WORKDIR /workspace

EXPOSE 22
ENTRYPOINT ["/entrypoint.sh"]

FROM base AS development


FROM base AS production