FROM hideregistry.azurecr.io/hide-env-base AS base

RUN mkdir /workspace \
  && chown -R devuser:devuser /workspace

RUN apk add build-base curl

USER devuser
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
USER root

RUN echo 'export PATH=$PATH:/home/devuser/.cargo/bin' >> /home/devuser/.profile

COPY motd /etc/motd
WORKDIR /workspace

FROM base AS development


FROM base AS production
