FROM alpine:latest AS base

RUN wget https://go.dev/dl/go1.24.2.linux-arm64.tar.gz \
  && tar -C /usr/local -xzf go1.24.2.linux-arm64.tar.gz \
  && echo "export PATH=\$PATH:/usr/local/go/bin" >> ~/.profile \
  && source ~/.profile
RUN apk add jq openssh openssh-server openssh-keygen supervisor
RUN ssh-keygen -A
RUN adduser -D -s /bin/sh devuser \
  && mkdir -p /home/devuser/.ssh \
  && chmod 700 /home/devuser/.ssh
RUN echo "PermitRootLogin no" >> /etc/ssh/sshd_config \
  && echo "PasswordAuthentication no" >> /etc/ssh/sshd_config \
  && echo "PubkeyAuthentication yes" >> /etc/ssh/sshd_config \
  && echo "AuthorizedKeysFile /home/devuser/.ssh/authorized_keys" >> /etc/ssh/sshd_config \
  && echo "AllowUsers devuser" >> /etc/ssh/sshd_config
WORKDIR /app
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENV PATH="/usr/local/go/bin:/root/go/bin:${PATH}"
COPY motd /etc/motd

FROM base AS development
COPY filesystem ./filesystem
RUN go install github.com/air-verse/air@v1.62.0
COPY envs/supervisord-dev.conf /etc/supervisord.conf

EXPOSE 22
ENTRYPOINT ["/entrypoint.sh"]

FROM base AS production
COPY filesystem ./filesystem
RUN cd filesystem && go build -o ./.build/main .
COPY envs/supervisord.conf /etc/supervisord.conf

EXPOSE 22
ENTRYPOINT ["/entrypoint.sh"]
